# Generated by Django 5.0.6 on 2024-06-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.CharField(choices=[('ST', 'Student'), ('EN', 'Enrollee')], default='EN', max_length=2),
        ),
    ]
