/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseComponentWithBorders: typeof import('./src/components/BaseComponentWithBorders.vue')['default']
    BaseComponentWithHeader: typeof import('./src/components/BaseComponentWithHeader.vue')['default']
    BuildingDetailsComponent: typeof import('./src/components/BuildingDetailsComponent.vue')['default']
    Button: typeof import('primevue/button')['default']
    DepartmentDetailsComponent: typeof import('./src/components/DepartmentDetailsComponent.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    MagnoliaFooter: typeof import('./src/components/MagnoliaFooter.vue')['default']
    MagnoliaHeader: typeof import('./src/components/MagnoliaHeader.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    ModalComponent: typeof import('./src/components/ModalWithLogoComponent.vue')['default']
    ModalWithLogoComponent: typeof import('./src/components/ModalWithLogoComponent.vue')['default']
    Password: typeof import('primevue/password')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RightSideBar: typeof import('./src/components/RightSideBar.vue')['default']
    RightSidePanel: typeof import('./src/components/RightSidePanel.vue')['default']
    RouteInputComponent: typeof import('./src/components/RouteInputComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import('primevue/skeleton')['default']
    TeacherDetailsComponent: typeof import('./src/components/TeacherDetailsComponent.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
}
