# Generated by Django 5.0.6 on 2024-05-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='token',
            field=models.CharField(max_length=128),
        ),
    ]
