# Generated by Django 5.0.6 on 2024-05-31 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_building_departments_alter_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='buildings', to='search.department'),
        ),
        migrations.CreateModel(
            name='ExtAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ext_attributes',
                'unique_together': {('name', 'value')},
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='ext_attributes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='search.extattribute'),
        ),
    ]
