# Generated by Django 5.0.6 on 2024-05-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_alter_building_departments_extattribute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ext_attributes',
            field=models.ManyToManyField(blank=True, related_name='departments', to='search.extattribute'),
        ),
    ]
