# Generated by Django 5.0.6 on 2024-06-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_building_ext_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='search.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ext_attributes',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='search.extattribute'),
        ),
    ]
